# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediapipe/framework/formats/wrapper_hand_tracker.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import landmark_pb2 as mediapipe_dot_framework_dot_formats_dot_landmark__pb2
import rect_pb2 as mediapipe_dot_framework_dot_formats_dot_rect__pb2
import detection_pb2 as mediapipe_dot_framework_dot_formats_dot_detection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediapipe/framework/formats/wrapper_hand_tracker.proto',
  package='mediapipe',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n6mediapipe/framework/formats/wrapper_hand_tracker.proto\x12\tmediapipe\x1a*mediapipe/framework/formats/landmark.proto\x1a&mediapipe/framework/formats/rect.proto\x1a+mediapipe/framework/formats/detection.proto\"\xa1\x01\n\x13WrapperHandTracking\x12\x34\n\tlandmarks\x18\x01 \x01(\x0b\x32!.mediapipe.NormalizedLandmarkList\x12\'\n\x04rect\x18\x02 \x01(\x0b\x32\x19.mediapipe.NormalizedRect\x12+\n\tdetection\x18\x03 \x01(\x0b\x32\x18.mediapipe.DetectionList'
  ,
  dependencies=[mediapipe_dot_framework_dot_formats_dot_landmark__pb2.DESCRIPTOR,mediapipe_dot_framework_dot_formats_dot_rect__pb2.DESCRIPTOR,mediapipe_dot_framework_dot_formats_dot_detection__pb2.DESCRIPTOR,])




_WRAPPERHANDTRACKING = _descriptor.Descriptor(
  name='WrapperHandTracking',
  full_name='mediapipe.WrapperHandTracking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='landmarks', full_name='mediapipe.WrapperHandTracking.landmarks', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rect', full_name='mediapipe.WrapperHandTracking.rect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection', full_name='mediapipe.WrapperHandTracking.detection', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=360,
)

_WRAPPERHANDTRACKING.fields_by_name['landmarks'].message_type = mediapipe_dot_framework_dot_formats_dot_landmark__pb2._NORMALIZEDLANDMARKLIST
_WRAPPERHANDTRACKING.fields_by_name['rect'].message_type = mediapipe_dot_framework_dot_formats_dot_rect__pb2._NORMALIZEDRECT
_WRAPPERHANDTRACKING.fields_by_name['detection'].message_type = mediapipe_dot_framework_dot_formats_dot_detection__pb2._DETECTIONLIST
DESCRIPTOR.message_types_by_name['WrapperHandTracking'] = _WRAPPERHANDTRACKING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WrapperHandTracking = _reflection.GeneratedProtocolMessageType('WrapperHandTracking', (_message.Message,), {
  'DESCRIPTOR' : _WRAPPERHANDTRACKING,
  '__module__' : 'mediapipe.framework.formats.wrapper_hand_tracker_pb2'
  # @@protoc_insertion_point(class_scope:mediapipe.WrapperHandTracking)
  })
_sym_db.RegisterMessage(WrapperHandTracking)


# @@protoc_insertion_point(module_scope)
